### ISSUE TITLE
Week 4 challenge using PDFs

### ISSUE THREAD

**Issue by Domsdorm** [DanielCCF/BotGamesAA#2]
Hi Daniel,

I really love your week 4 script as it was easy to understand for someone like me who is a novice at python. I was wondering if instead of the challenge's .tiff images, PDFs were used. Is it possible to change your code a little to scan the PDFs and still be able to input them for the challenge? And if possible how.

Thanks for your help!

**Comment by DanielCCF** [comment]
Hi Domsdorm!

Thank you for commenting. I'm glad you liked the solution :)

The OCR engine I've used, Tesseract, is limited to use images only. To work with PDFs, you need to convert to images first. To this, the package 'pdf2image' does the job.

It's good pointing that converting would not be the difficult part. This modification requires just one more function, like convert_invoice_from_pdf_to_image, convert_pdf_to_image, and so on. This would happen at the pre-processing part.

The part I would be worried about is the ReGex, because the outcome from Tesseract could be different enough to the regex pattern stop working properly. 

The worst-case scenario is not only the Regex functions stop working, but it generates images that 1 pattern doesn't fit for all the invoices, like the function 'get_invoice_total(invoiceData)' does. In this nightmar... I mean, case, the Regex function to identify the type of invoice would be needed to make further modifications easier to manage.

If you have further questions, you can reach me with no worries. I can take a while to answer, but I'll do for sure.

**Comment by DanielCCF** [comment]
Hi Domsdorm!

I'm closing this issue today, but feel free to comment if you have any questions or ideas.

Thanks!
